"""
config.py — The Gentlemen's Game 2026
All constants, player database, and schedule data.
"""

# ─────────────────────────────────────────────
# FIREBASE
# ─────────────────────────────────────────────
FIREBASE_PROJECT_ID = "the-gentlemen-s-game-2026"

# ─────────────────────────────────────────────
# ESPN
# ─────────────────────────────────────────────
ESPN_SERIES_ID   = "1510719"
ESPN_SERIES_SLUG = "ipl-2026-1510719"

ESPN_SCHEDULE_API = (
    "https://hs-consumer-api.espncricinfo.com/v1/pages/series/schedule"
    "?lang=en&seriesId={series_id}"
)
ESPN_MATCH_SUMMARY_API = (
    "https://hs-consumer-api.espncricinfo.com/v1/pages/match/summary"
    "?lang=en&seriesId={series_id}&matchId={match_id}"
)
ESPN_MATCH_PAGE = (
    "https://www.espncricinfo.com/series/{series_slug}/{match_slug}/full-scorecard"
)

# ─────────────────────────────────────────────
# NOTIFICATIONS
# ─────────────────────────────────────────────
NOTIFY_EMAIL = "thegentlemensgamecirca2025@gmail.com"

# ─────────────────────────────────────────────
# MATCH SCHEDULE  (match_num, home, away, gw)
# ─────────────────────────────────────────────
SCHEDULE = [
    (1,  'RCB',  'SRH',  1), (2,  'MI',   'KKR',  1), (3,  'RR',   'CSK',  1),
    (4,  'PBKS', 'GT',   1), (5,  'LSG',  'DC',   1), (6,  'KKR',  'SRH',  1),
    (7,  'CSK',  'PBKS', 1),
    (8,  'DC',   'MI',   2), (9,  'GT',   'RR',   2), (10, 'SRH',  'LSG',  2),
    (11, 'RCB',  'CSK',  2), (12, 'KKR',  'PBKS', 2), (13, 'RR',   'MI',   2),
    (14, 'DC',   'GT',   2), (15, 'KKR',  'LSG',  2), (16, 'RR',   'RCB',  2),
    (17, 'PBKS', 'SRH',  3), (18, 'CSK',  'DC',   3), (19, 'LSG',  'GT',   3),
    (20, 'MI',   'RCB',  3), (21, 'SRH',  'RR',   3), (22, 'CSK',  'KKR',  3),
    (23, 'RCB',  'LSG',  3), (24, 'MI',   'PBKS', 3), (25, 'GT',   'KKR',  3),
    (26, 'RCB',  'DC',   4), (27, 'SRH',  'CSK',  4), (28, 'KKR',  'RR',   4),
    (29, 'PBKS', 'LSG',  4), (30, 'GT',   'MI',   4), (31, 'SRH',  'DC',   4),
    (32, 'LSG',  'RR',   4), (33, 'MI',   'CSK',  4), (34, 'RCB',  'GT',   4),
    (35, 'DC',   'PBKS', 5), (36, 'RR',   'SRH',  5), (37, 'GT',   'CSK',  5),
    (38, 'LSG',  'KKR',  5), (39, 'DC',   'RCB',  5), (40, 'PBKS', 'RR',   5),
    (41, 'MI',   'SRH',  5), (42, 'GT',   'RCB',  5), (43, 'RR',   'DC',   5),
    (44, 'CSK',  'MI',   6), (45, 'SRH',  'KKR',  6), (46, 'GT',   'PBKS', 6),
    (47, 'MI',   'LSG',  6), (48, 'DC',   'CSK',  6), (49, 'SRH',  'PBKS', 6),
    (50, 'LSG',  'RCB',  6), (51, 'DC',   'KKR',  6),
    (52, 'RR',   'GT',   7), (53, 'CSK',  'LSG',  7), (54, 'RCB',  'MI',   7),
    (55, 'PBKS', 'DC',   7), (56, 'GT',   'SRH',  7), (57, 'RCB',  'KKR',  7),
    (58, 'PBKS', 'MI',   7), (59, 'LSG',  'CSK',  7),
    (60, 'KKR',  'GT',   8), (61, 'PBKS', 'RCB',  8), (62, 'DC',   'RR',   8),
    (63, 'CSK',  'SRH',  8), (64, 'RR',   'LSG',  8), (65, 'KKR',  'MI',   8),
    (66, 'CSK',  'GT',   8), (67, 'SRH',  'RCB',  8),
    (68, 'LSG',  'PBKS', 9), (69, 'MI',   'RR',   9), (70, 'KKR',  'DC',   9),
    (71, 'TBD',  'TBD',  10),(72, 'TBD',  'TBD',  10),(73, 'TBD',  'TBD',  10),
    (74, 'TBD',  'TBD',  10),
]

# Build quick lookups
MATCH_NUM_TO_GW   = {m[0]: m[3] for m in SCHEDULE}
TEAMS_TO_MATCH    = {frozenset([m[1], m[2]]): m[0] for m in SCHEDULE if m[1] != 'TBD'}

TEAM_ALIASES = {
    'royal challengers bengaluru': 'RCB', 'rcb': 'RCB', 'bengaluru': 'RCB', 'bangalore': 'RCB',
    'sunrisers hyderabad': 'SRH', 'srh': 'SRH', 'hyderabad': 'SRH', 'sunrisers': 'SRH',
    'mumbai indians': 'MI',  'mi': 'MI',  'mumbai': 'MI',
    'kolkata knight riders': 'KKR', 'kkr': 'KKR', 'kolkata': 'KKR',
    'chennai super kings': 'CSK', 'csk': 'CSK', 'chennai': 'CSK',
    'rajasthan royals': 'RR', 'rr': 'RR', 'rajasthan': 'RR',
    'punjab kings': 'PBKS', 'pbks': 'PBKS', 'punjab': 'PBKS',
    'gujarat titans': 'GT', 'gt': 'GT', 'gujarat': 'GT',
    'lucknow super giants': 'LSG', 'lsg': 'LSG', 'lucknow': 'LSG',
    'delhi capitals': 'DC', 'dc': 'DC', 'delhi': 'DC',
}

# ─────────────────────────────────────────────
# PLAYER DATABASE  (251 players)
# ─────────────────────────────────────────────
ALL_PLAYERS = {
    1:   {'name': 'Sanju Samson',         'team': 'CSK',  'nat': 'Indian',   'cat': 'Wicketkeeper', 'price': 18},
    2:   {'name': 'Ruturaj Gaikwad',      'team': 'CSK',  'nat': 'Indian',   'cat': 'Batter',       'price': 15},
    3:   {'name': 'Mitchell Starc',       'team': 'DC',   'nat': 'Overseas', 'cat': 'Bowler',       'price': 15},
    4:   {'name': 'Axar Patel',           'team': 'DC',   'nat': 'Indian',   'cat': 'All-rounder',  'price': 15},
    5:   {'name': 'Kuldeep Yadav',        'team': 'DC',   'nat': 'Indian',   'cat': 'Bowler',       'price': 15},
    6:   {'name': 'KL Rahul',             'team': 'DC',   'nat': 'Indian',   'cat': 'Wicketkeeper', 'price': 15},
    7:   {'name': 'Rashid Khan',          'team': 'GT',   'nat': 'Overseas', 'cat': 'All-rounder',  'price': 15},
    8:   {'name': 'Sai Sudharsan',        'team': 'GT',   'nat': 'Indian',   'cat': 'Batter',       'price': 15},
    9:   {'name': 'Shubman Gill',         'team': 'GT',   'nat': 'Indian',   'cat': 'Batter',       'price': 15},
    10:  {'name': 'Jos Buttler',          'team': 'GT',   'nat': 'Overseas', 'cat': 'Wicketkeeper', 'price': 15},
    11:  {'name': 'Cameron Green',        'team': 'KKR',  'nat': 'Overseas', 'cat': 'All-rounder',  'price': 15},
    12:  {'name': 'Sunil Narine',         'team': 'KKR',  'nat': 'Overseas', 'cat': 'All-rounder',  'price': 15},
    13:  {'name': 'Varun Chakravarthy',   'team': 'KKR',  'nat': 'Indian',   'cat': 'Bowler',       'price': 15},
    14:  {'name': 'Mitchell Marsh',       'team': 'LSG',  'nat': 'Overseas', 'cat': 'Batter',       'price': 15},
    15:  {'name': 'Nicholas Pooran',      'team': 'LSG',  'nat': 'Overseas', 'cat': 'Wicketkeeper', 'price': 15},
    16:  {'name': 'Hardik Pandya',        'team': 'MI',   'nat': 'Indian',   'cat': 'All-rounder',  'price': 18},
    17:  {'name': 'Suryakumar Yadav',     'team': 'MI',   'nat': 'Indian',   'cat': 'Batter',       'price': 18},
    18:  {'name': 'Jasprit Bumrah',       'team': 'MI',   'nat': 'Indian',   'cat': 'Bowler',       'price': 18},
    19:  {'name': 'Shreyas Iyer',         'team': 'PBKS', 'nat': 'Indian',   'cat': 'Batter',       'price': 15},
    20:  {'name': 'Arshdeep Singh',       'team': 'PBKS', 'nat': 'Indian',   'cat': 'Bowler',       'price': 15},
    21:  {'name': 'Virat Kohli',          'team': 'RCB',  'nat': 'Indian',   'cat': 'Batter',       'price': 18},
    22:  {'name': 'Josh Hazlewood',       'team': 'RCB',  'nat': 'Overseas', 'cat': 'Bowler',       'price': 15},
    23:  {'name': 'Ravindra Jadeja',      'team': 'RR',   'nat': 'Indian',   'cat': 'All-rounder',  'price': 15},
    24:  {'name': 'Riyan Parag',          'team': 'RR',   'nat': 'Indian',   'cat': 'All-rounder',  'price': 15},
    25:  {'name': 'Yashasvi Jaiswal',     'team': 'RR',   'nat': 'Indian',   'cat': 'Batter',       'price': 18},
    26:  {'name': 'Abhishek Sharma',      'team': 'SRH',  'nat': 'Indian',   'cat': 'All-rounder',  'price': 15},
    27:  {'name': 'Pat Cummins',          'team': 'SRH',  'nat': 'Overseas', 'cat': 'All-rounder',  'price': 15},
    28:  {'name': 'Travis Head',          'team': 'SRH',  'nat': 'Overseas', 'cat': 'Batter',       'price': 15},
    29:  {'name': 'Heinrich Klaasen',     'team': 'SRH',  'nat': 'Overseas', 'cat': 'Wicketkeeper', 'price': 15},
    30:  {'name': 'Ayush Mhatre',         'team': 'CSK',  'nat': 'Indian',   'cat': 'Batter',       'price': 10},
    31:  {'name': 'Shivam Dube',          'team': 'CSK',  'nat': 'Indian',   'cat': 'All-rounder',  'price': 10},
    32:  {'name': 'Dewald Brevis',        'team': 'CSK',  'nat': 'Overseas', 'cat': 'Batter',       'price': 10},
    33:  {'name': 'Khaleel Ahmed',        'team': 'CSK',  'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    34:  {'name': 'Noor Ahmad',           'team': 'CSK',  'nat': 'Overseas', 'cat': 'Bowler',       'price': 10},
    35:  {'name': 'Tristan Stubbs',       'team': 'DC',   'nat': 'Overseas', 'cat': 'Batter',       'price': 10},
    36:  {'name': 'Glenn Phillips',       'team': 'GT',   'nat': 'Overseas', 'cat': 'All-rounder',  'price': 10},
    37:  {'name': 'Kagiso Rabada',        'team': 'GT',   'nat': 'Overseas', 'cat': 'Bowler',       'price': 10},
    38:  {'name': 'Mohammed Siraj',       'team': 'GT',   'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    39:  {'name': 'Prasidh Krishna',      'team': 'GT',   'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    40:  {'name': 'Sai Kishore',          'team': 'GT',   'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    41:  {'name': 'Ajinkya Rahane',       'team': 'KKR',  'nat': 'Indian',   'cat': 'Batter',       'price': 10},
    42:  {'name': 'Rinku Singh',          'team': 'KKR',  'nat': 'Indian',   'cat': 'Batter',       'price': 10},
    43:  {'name': 'Harshit Rana',         'team': 'KKR',  'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    44:  {'name': 'Matheesha Pathirana',  'team': 'KKR',  'nat': 'Overseas', 'cat': 'Bowler',       'price': 10},
    45:  {'name': 'Vaibhav Arora',        'team': 'KKR',  'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    46:  {'name': 'Finn Allen',           'team': 'KKR',  'nat': 'Overseas', 'cat': 'Wicketkeeper', 'price': 10},
    47:  {'name': 'Rishabh Pant',         'team': 'LSG',  'nat': 'Indian',   'cat': 'Wicketkeeper', 'price': 10},
    48:  {'name': 'Aiden Markram',        'team': 'LSG',  'nat': 'Overseas', 'cat': 'All-rounder',  'price': 10},
    49:  {'name': 'Avesh Khan',           'team': 'LSG',  'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    50:  {'name': 'Digvesh Rathi',        'team': 'LSG',  'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    51:  {'name': 'Mohammed Shami',       'team': 'LSG',  'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    52:  {'name': 'Mitchell Santner',     'team': 'MI',   'nat': 'Overseas', 'cat': 'All-rounder',  'price': 10},
    53:  {'name': 'Will Jacks',           'team': 'MI',   'nat': 'Overseas', 'cat': 'All-rounder',  'price': 10},
    54:  {'name': 'Rohit Sharma',         'team': 'MI',   'nat': 'Indian',   'cat': 'Batter',       'price': 10},
    55:  {'name': 'Tilak Varma',          'team': 'MI',   'nat': 'Indian',   'cat': 'Batter',       'price': 10},
    56:  {'name': 'Deepak Chahar',        'team': 'MI',   'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    57:  {'name': 'Trent Boult',          'team': 'MI',   'nat': 'Overseas', 'cat': 'Bowler',       'price': 10},
    58:  {'name': 'Quinton De Kock',      'team': 'MI',   'nat': 'Overseas', 'cat': 'Wicketkeeper', 'price': 10},
    59:  {'name': 'Marco Jansen',         'team': 'PBKS', 'nat': 'Overseas', 'cat': 'All-rounder',  'price': 13},
    60:  {'name': 'Marcus Stoinis',       'team': 'PBKS', 'nat': 'Overseas', 'cat': 'All-rounder',  'price': 10},
    61:  {'name': 'Priyansh Arya',        'team': 'PBKS', 'nat': 'Indian',   'cat': 'Batter',       'price':  7},
    62:  {'name': 'Shashank Singh',       'team': 'PBKS', 'nat': 'Indian',   'cat': 'Batter',       'price': 10},
    63:  {'name': 'Yuzvendra Chahal',     'team': 'PBKS', 'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    64:  {'name': 'Prabhsimran Singh',    'team': 'PBKS', 'nat': 'Indian',   'cat': 'Wicketkeeper', 'price': 10},
    65:  {'name': 'Phil Salt',            'team': 'RCB',  'nat': 'Overseas', 'cat': 'Wicketkeeper', 'price': 10},
    66:  {'name': 'Jacob Bethell',        'team': 'RCB',  'nat': 'Overseas', 'cat': 'All-rounder',  'price': 10},
    67:  {'name': 'Krunal Pandya',        'team': 'RCB',  'nat': 'Indian',   'cat': 'All-rounder',  'price': 10},
    68:  {'name': 'Venkatesh Iyer',       'team': 'RCB',  'nat': 'Indian',   'cat': 'All-rounder',  'price': 10},
    69:  {'name': 'Rajat Patidar',        'team': 'RCB',  'nat': 'Indian',   'cat': 'Batter',       'price': 10},
    70:  {'name': 'Bhuvneshwar Kumar',    'team': 'RCB',  'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    71:  {'name': 'Yash Dayal',           'team': 'RCB',  'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    72:  {'name': 'Jitesh Sharma',        'team': 'RCB',  'nat': 'Indian',   'cat': 'Wicketkeeper', 'price': 10},
    73:  {'name': 'Vaibhav Suryavanshi',  'team': 'RR',   'nat': 'Indian',   'cat': 'Batter',       'price': 10},
    74:  {'name': 'Sam Curran',           'team': 'RR',   'nat': 'Overseas', 'cat': 'All-rounder',  'price': 10},
    75:  {'name': 'Shimron Hetmyer',      'team': 'RR',   'nat': 'Overseas', 'cat': 'Batter',       'price': 10},
    76:  {'name': 'Jofra Archer',         'team': 'RR',   'nat': 'Overseas', 'cat': 'Bowler',       'price': 10},
    77:  {'name': 'Ravi Bishnoi',         'team': 'RR',   'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    78:  {'name': 'Dhruv Jurel',          'team': 'RR',   'nat': 'Indian',   'cat': 'Wicketkeeper', 'price': 10},
    79:  {'name': 'Ishan Kishan',         'team': 'SRH',  'nat': 'Indian',   'cat': 'Wicketkeeper', 'price': 10},
    80:  {'name': 'Harshal Patel',        'team': 'SRH',  'nat': 'Indian',   'cat': 'Bowler',       'price': 10},
    81:  {'name': 'Prashant Veer',        'team': 'CSK',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  7},
    82:  {'name': 'Anshul Kamboj',        'team': 'CSK',  'nat': 'Indian',   'cat': 'Bowler',       'price':  7},
    83:  {'name': 'Nathan Ellis',         'team': 'CSK',  'nat': 'Overseas', 'cat': 'Bowler',       'price':  7},
    84:  {'name': 'MS Dhoni',             'team': 'CSK',  'nat': 'Indian',   'cat': 'Wicketkeeper', 'price':  7},
    85:  {'name': 'Auqib Nabi',           'team': 'DC',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  7},
    86:  {'name': 'Vipraj Nigam',         'team': 'DC',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  7},
    87:  {'name': 'Ashutosh Sharma',      'team': 'DC',   'nat': 'Indian',   'cat': 'Batter',       'price':  7},
    88:  {'name': 'David Miller',         'team': 'DC',   'nat': 'Overseas', 'cat': 'Batter',       'price':  7},
    89:  {'name': 'Karun Nair',           'team': 'DC',   'nat': 'Indian',   'cat': 'Batter',       'price':  7},
    90:  {'name': 'Nitish Rana',          'team': 'DC',   'nat': 'Indian',   'cat': 'Batter',       'price':  7},
    91:  {'name': 'Pathum Nissanka',      'team': 'DC',   'nat': 'Overseas', 'cat': 'Batter',       'price':  7},
    92:  {'name': 'Lungi Ngidi',          'team': 'DC',   'nat': 'Overseas', 'cat': 'Bowler',       'price':  7},
    93:  {'name': 'Mukesh Kumar',         'team': 'DC',   'nat': 'Indian',   'cat': 'Bowler',       'price':  7},
    94:  {'name': 'T Natarajan',          'team': 'DC',   'nat': 'Indian',   'cat': 'Bowler',       'price':  7},
    95:  {'name': 'Abishek Porel',        'team': 'DC',   'nat': 'Indian',   'cat': 'Wicketkeeper', 'price':  7},
    96:  {'name': 'Jason Holder',         'team': 'GT',   'nat': 'Overseas', 'cat': 'All-rounder',  'price':  7},
    97:  {'name': 'Rahul Tewatia',        'team': 'GT',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  7},
    98:  {'name': 'Washington Sundar',    'team': 'GT',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  7},
    99:  {'name': 'M Shahrukh Khan',      'team': 'GT',   'nat': 'Indian',   'cat': 'Batter',       'price':  7},
    100: {'name': 'Tim Seifert',          'team': 'KKR',  'nat': 'Overseas', 'cat': 'Wicketkeeper', 'price':  7},
    101: {'name': 'Rovman Powell',        'team': 'KKR',  'nat': 'Overseas', 'cat': 'All-rounder',  'price':  7},
    102: {'name': 'Angkrish Raghuvanshi', 'team': 'KKR',  'nat': 'Indian',   'cat': 'Batter',       'price':  7},
    103: {'name': 'Akash Deep',           'team': 'KKR',  'nat': 'Indian',   'cat': 'Bowler',       'price':  7},
    104: {'name': 'Blessing Muzarabani',  'team': 'KKR',  'nat': 'Overseas', 'cat': 'Bowler',       'price':  7},
    105: {'name': 'Ayush Badoni',         'team': 'LSG',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  7},
    106: {'name': 'Shahbaz Ahmed',        'team': 'LSG',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  7},
    107: {'name': 'Wanindu Hasaranga',    'team': 'LSG',  'nat': 'Overseas', 'cat': 'All-rounder',  'price':  7},
    108: {'name': 'Abdul Samad',          'team': 'LSG',  'nat': 'Indian',   'cat': 'Batter',       'price':  7},
    109: {'name': 'Anrich Nortje',        'team': 'LSG',  'nat': 'Overseas', 'cat': 'Bowler',       'price':  7},
    110: {'name': 'Mayank Yadav',         'team': 'LSG',  'nat': 'Indian',   'cat': 'Bowler',       'price':  7},
    111: {'name': 'Mohsin Khan',          'team': 'LSG',  'nat': 'Indian',   'cat': 'Bowler',       'price':  7},
    112: {'name': 'Josh Inglis',          'team': 'LSG',  'nat': 'Overseas', 'cat': 'Wicketkeeper', 'price':  7},
    113: {'name': 'Corbin Bosch',         'team': 'MI',   'nat': 'Overseas', 'cat': 'All-rounder',  'price':  7},
    114: {'name': 'Shardul Thakur',       'team': 'MI',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  7},
    115: {'name': 'Naman Dhir',           'team': 'MI',   'nat': 'Indian',   'cat': 'Batter',       'price':  7},
    116: {'name': 'Sherfane Rutherford',  'team': 'MI',   'nat': 'Overseas', 'cat': 'Batter',       'price':  7},
    117: {'name': 'Ryan Rickelton',       'team': 'MI',   'nat': 'Overseas', 'cat': 'Wicketkeeper', 'price':  7},
    118: {'name': 'Azmatullah Omarzai',   'team': 'PBKS', 'nat': 'Overseas', 'cat': 'All-rounder',  'price':  7},
    119: {'name': 'Harpreet Brar',        'team': 'PBKS', 'nat': 'Indian',   'cat': 'All-rounder',  'price':  7},
    120: {'name': 'Nehal Wadhera',        'team': 'PBKS', 'nat': 'Indian',   'cat': 'Batter',       'price':  7},
    121: {'name': 'Lockie Ferguson',      'team': 'PBKS', 'nat': 'Overseas', 'cat': 'Bowler',       'price':  7},
    122: {'name': 'Vijaykumar Vyshak',    'team': 'PBKS', 'nat': 'Indian',   'cat': 'Bowler',       'price':  7},
    123: {'name': 'Romario Shepherd',     'team': 'RCB',  'nat': 'Overseas', 'cat': 'All-rounder',  'price':  7},
    124: {'name': 'Devdutt Padikkal',     'team': 'RCB',  'nat': 'Indian',   'cat': 'Batter',       'price':  7},
    125: {'name': 'Tim David',            'team': 'RCB',  'nat': 'Overseas', 'cat': 'Batter',       'price':  7},
    126: {'name': 'Suyash Sharma',        'team': 'RCB',  'nat': 'Indian',   'cat': 'Bowler',       'price':  7},
    127: {'name': 'Sandeep Sharma',       'team': 'RR',   'nat': 'Indian',   'cat': 'Bowler',       'price':  7},
    128: {'name': 'Tushar Deshpande',     'team': 'RR',   'nat': 'Indian',   'cat': 'Bowler',       'price':  7},
    129: {'name': 'Liam Livingstone',     'team': 'SRH',  'nat': 'Overseas', 'cat': 'All-rounder',  'price':  7},
    130: {'name': 'Nitish Kumar Reddy',   'team': 'SRH',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  7},
    131: {'name': 'Aniket Verma',         'team': 'SRH',  'nat': 'Indian',   'cat': 'Batter',       'price':  7},
    132: {'name': 'Jaydev Unadkat',       'team': 'SRH',  'nat': 'Indian',   'cat': 'Bowler',       'price':  7},
    133: {'name': 'Zeeshan Ansari',       'team': 'SRH',  'nat': 'Indian',   'cat': 'Bowler',       'price':  7},
    134: {'name': 'Aman Khan',            'team': 'CSK',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    135: {'name': 'Jamie Overton',        'team': 'CSK',  'nat': 'Overseas', 'cat': 'All-rounder',  'price':  4},
    136: {'name': 'Matthew Short',        'team': 'CSK',  'nat': 'Overseas', 'cat': 'All-rounder',  'price':  4},
    137: {'name': 'Ramakrishna Ghosh',    'team': 'CSK',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    138: {'name': 'Sarfaraz Khan',        'team': 'CSK',  'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    139: {'name': 'Akeal Hosein',         'team': 'CSK',  'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    140: {'name': 'Gurjapneet Singh',     'team': 'CSK',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    141: {'name': 'Matt Henry',           'team': 'CSK',  'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    142: {'name': 'Mukesh Choudhary',     'team': 'CSK',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    143: {'name': 'Rahul Chahar',         'team': 'CSK',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    144: {'name': 'Shreyas Gopal',        'team': 'CSK',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    145: {'name': 'Zak Foulkes',          'team': 'CSK',  'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    146: {'name': 'Kartik Sharma',        'team': 'CSK',  'nat': 'Indian',   'cat': 'Wicketkeeper', 'price':  4},
    147: {'name': 'Urvil Patel',          'team': 'CSK',  'nat': 'Indian',   'cat': 'Wicketkeeper', 'price':  4},
    148: {'name': 'Ajay Mandal',          'team': 'DC',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    149: {'name': 'Madhav Tiwari',        'team': 'DC',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    150: {'name': 'Tripurana Vijay',      'team': 'DC',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    151: {'name': 'Prithvi Shaw',         'team': 'DC',   'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    152: {'name': 'Sahil Parakh',         'team': 'DC',   'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    153: {'name': 'Sameer Rizvi',         'team': 'DC',   'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    154: {'name': 'Dushmantha Chameera',  'team': 'DC',   'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    155: {'name': 'Kyle Jamieson',        'team': 'DC',   'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    156: {'name': 'Ben Duckett',          'team': 'DC',   'nat': 'Overseas', 'cat': 'Wicketkeeper', 'price':  4},
    157: {'name': 'Arshad Khan',          'team': 'GT',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    158: {'name': 'Nishant Sindhu',       'team': 'GT',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    159: {'name': 'Ashok Sharma',         'team': 'GT',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    160: {'name': 'Gurnoor Brar',         'team': 'GT',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    161: {'name': 'Ishant Sharma',        'team': 'GT',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    162: {'name': 'Jayant Yadav',         'team': 'GT',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    163: {'name': 'Luke Wood',            'team': 'GT',   'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    164: {'name': 'Manav Suthar',         'team': 'GT',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    165: {'name': 'Prithviraj Yarra',     'team': 'GT',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    166: {'name': 'Anuj Rawat',           'team': 'GT',   'nat': 'Indian',   'cat': 'Wicketkeeper', 'price':  4},
    167: {'name': 'Kumar Kushagra',       'team': 'GT',   'nat': 'Indian',   'cat': 'Wicketkeeper', 'price':  4},
    168: {'name': 'Tom Banton',           'team': 'GT',   'nat': 'Overseas', 'cat': 'Wicketkeeper', 'price':  4},
    169: {'name': 'Anukul Roy',           'team': 'KKR',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    170: {'name': 'Daksh Kamra',          'team': 'KKR',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    171: {'name': 'Rachin Ravindra',      'team': 'KKR',  'nat': 'Overseas', 'cat': 'All-rounder',  'price':  4},
    172: {'name': 'Ramandeep Singh',      'team': 'KKR',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    173: {'name': 'Sarthak Ranjan',       'team': 'KKR',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    174: {'name': 'Manish Pandey',        'team': 'KKR',  'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    175: {'name': 'Rahul Tripathi',       'team': 'KKR',  'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    176: {'name': 'Kartik Tyagi',         'team': 'KKR',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    177: {'name': 'Prashant Solanki',     'team': 'KKR',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    178: {'name': 'Umran Malik',          'team': 'KKR',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    179: {'name': 'Tejasvi Singh',        'team': 'KKR',  'nat': 'Indian',   'cat': 'Wicketkeeper', 'price':  4},
    180: {'name': 'Arshin Kulkarni',      'team': 'LSG',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    181: {'name': 'Naman Tiwari',         'team': 'LSG',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    182: {'name': 'Akshat Raghuwanshi',   'team': 'LSG',  'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    183: {'name': 'Himmat Singh',         'team': 'LSG',  'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    184: {'name': 'Matthew Breetzke',     'team': 'LSG',  'nat': 'Overseas', 'cat': 'Batter',       'price':  4},
    185: {'name': 'Akash Singh',          'team': 'LSG',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    186: {'name': 'Arjun Tendulkar',      'team': 'LSG',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    187: {'name': 'M Siddharth',          'team': 'LSG',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    188: {'name': 'Prince Yadav',         'team': 'LSG',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    189: {'name': 'Mukul Choudhary',      'team': 'LSG',  'nat': 'Indian',   'cat': 'Wicketkeeper', 'price':  4},
    190: {'name': 'Atharva Ankolekar',    'team': 'MI',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    191: {'name': 'Mayank Rawat',         'team': 'MI',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    192: {'name': 'Raj Bawa',             'team': 'MI',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    193: {'name': 'Danish Malewar',       'team': 'MI',   'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    194: {'name': 'Allah Ghazanfar',      'team': 'MI',   'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    195: {'name': 'Ashwani Kumar',        'team': 'MI',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    196: {'name': 'Mayank Markande',      'team': 'MI',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    197: {'name': 'Mohammad Izhar',       'team': 'MI',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    198: {'name': 'Raghu Sharma',         'team': 'MI',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    199: {'name': 'Robin Minz',           'team': 'MI',   'nat': 'Indian',   'cat': 'Wicketkeeper', 'price':  4},
    200: {'name': 'Cooper Connolly',      'team': 'PBKS', 'nat': 'Overseas', 'cat': 'All-rounder',  'price':  4},
    201: {'name': 'Mitch Owen',           'team': 'PBKS', 'nat': 'Overseas', 'cat': 'All-rounder',  'price':  4},
    202: {'name': 'Musheer Khan',         'team': 'PBKS', 'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    203: {'name': 'Suryansh Shedge',      'team': 'PBKS', 'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    204: {'name': 'Harnoor Pannu',        'team': 'PBKS', 'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    205: {'name': 'Pyla Avinash',         'team': 'PBKS', 'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    206: {'name': 'Ben Dwarshuis',        'team': 'PBKS', 'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    207: {'name': 'Vishal Nishad',        'team': 'PBKS', 'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    208: {'name': 'Xavier Bartlett',      'team': 'PBKS', 'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    209: {'name': 'Yash Thakur',          'team': 'PBKS', 'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    210: {'name': 'Vishnu Vinod',         'team': 'PBKS', 'nat': 'Indian',   'cat': 'Wicketkeeper', 'price':  4},
    211: {'name': 'Kanishk Chouhan',      'team': 'RCB',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    212: {'name': 'Mangesh Yadav',        'team': 'RCB',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    213: {'name': 'Satvik Deswal',        'team': 'RCB',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    214: {'name': 'Swapnil Singh',        'team': 'RCB',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    215: {'name': 'Vicky Ostwal',         'team': 'RCB',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    216: {'name': 'Vihaan Malhotra',      'team': 'RCB',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    217: {'name': 'Jordan Cox',           'team': 'RCB',  'nat': 'Overseas', 'cat': 'Batter',       'price':  4},
    218: {'name': 'Abhinandan Singh',     'team': 'RCB',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    219: {'name': 'Jacob Duffy',          'team': 'RCB',  'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    220: {'name': 'Nuwan Thushara',       'team': 'RCB',  'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    221: {'name': 'Rasikh Salam',         'team': 'RCB',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    222: {'name': 'Donovan Ferreira',     'team': 'RR',   'nat': 'Overseas', 'cat': 'All-rounder',  'price':  4},
    223: {'name': 'Yudhvir Singh Charak', 'team': 'RR',   'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    224: {'name': 'Aman Rao',             'team': 'RR',   'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    225: {'name': 'Lhuan-dre Pretorius',  'team': 'RR',   'nat': 'Overseas', 'cat': 'Batter',       'price':  4},
    226: {'name': 'Shubham Dubey',        'team': 'RR',   'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    227: {'name': 'Adam Milne',           'team': 'RR',   'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    228: {'name': 'Brijesh Sharma',       'team': 'RR',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    229: {'name': 'Kuldeep Sen',          'team': 'RR',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    230: {'name': 'Kwena Maphaka',        'team': 'RR',   'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    231: {'name': 'Nandre Burger',        'team': 'RR',   'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    232: {'name': 'Sushant Mishra',       'team': 'RR',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    233: {'name': 'Vignesh Puthur',       'team': 'RR',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    234: {'name': 'Yash Raj Punja',       'team': 'RR',   'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    235: {'name': 'Ravi Singh',           'team': 'RR',   'nat': 'Indian',   'cat': 'Wicketkeeper', 'price':  4},
    236: {'name': 'Harsh Dubey',          'team': 'SRH',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    237: {'name': 'Jack Edwards',         'team': 'SRH',  'nat': 'Overseas', 'cat': 'All-rounder',  'price':  4},
    238: {'name': 'Kamindu Mendis',       'team': 'SRH',  'nat': 'Overseas', 'cat': 'All-rounder',  'price':  4},
    239: {'name': 'Shivang Kumar',        'team': 'SRH',  'nat': 'Indian',   'cat': 'All-rounder',  'price':  4},
    240: {'name': 'R Smaran',             'team': 'SRH',  'nat': 'Indian',   'cat': 'Batter',       'price':  4},
    241: {'name': 'Amit Kumar',           'team': 'SRH',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    242: {'name': 'Brydon Carse',         'team': 'SRH',  'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    243: {'name': 'Eshan Malinga',        'team': 'SRH',  'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    244: {'name': 'Krains Fuletra',       'team': 'SRH',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    245: {'name': 'Onkar Tarmale',        'team': 'SRH',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    246: {'name': 'Praful Hinge',         'team': 'SRH',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    247: {'name': 'Sakib Hussain',        'team': 'SRH',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    248: {'name': 'Shivam Mavi',          'team': 'SRH',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
    249: {'name': 'Salil Arora',          'team': 'SRH',  'nat': 'Indian',   'cat': 'Wicketkeeper', 'price':  4},
    # Mid-season replacements
    250: {'name': 'David Payne',          'team': 'SRH',  'nat': 'Overseas', 'cat': 'Bowler',       'price':  4},
    251: {'name': 'Saurabh Dubey',        'team': 'KKR',  'nat': 'Indian',   'cat': 'Bowler',       'price':  4},
}

# Build lookup dicts
ID_TO_NAME = {str(pid): p['name'] for pid, p in ALL_PLAYERS.items()}
NAME_TO_ID = {p['name']: pid for pid, p in ALL_PLAYERS.items()}
